version: "3"

services:
  nginx:
    build: ./nginx
    restart: always
    depends_on: 
      - covidian_client
      - covidian_server
    ports: 
      - "3050:80"

  covidian_client:
    tty: true
    build: ./client
    restart: always
    depends_on: 
      - covidian_server
      - covidian_predict

  covidian_server:
    build: ./server
    environment:
      - covidian_server_internal_mongo_url=mongodb+srv://amogh123:amogh123@amogh-first-cluster-vdru3.mongodb.net/twitter

  covidian_predict:
    build: ./data_science/predict
